name: pylint

on:
  workflow_call:
    inputs: {}
    secrets: {}

jobs:
  pylint:
    runs-on: alpine-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running YAMLlint
      uses: "docker://pipelinecomponents/pylint:latest"
      with:
        args: pylint pycli/
