baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'PyCLI'
theme = 'github.com/alex-shpak/hugo-book'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookSection = '*'