name: lint

on:
  workflow_call:
    inputs: 
      dev_image_name:
        required: true
        type: string
    secrets: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.dev_image_name }}:latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Running pytest
      run: make unit-test